"use client"

import { DataTable } from "@/components/ui/data-table";
import { investorTableColumns } from "./investorTableColumns";
import { usePathname, useRouter } from "next/navigation";

export default function InvestorsListTable() {
  const data: any = [
    {
      "id": "1",
      "name": "Alice Johnson",
      "walletAddress": "0xAf5D745F5370d8B2d95ef2ae",
      "investorType": "Individual",
      "business": true,
      "residency": "US",
      "nationality": "American",
      "status": "Verified",
    },
    {
      "id": "2",
      "name": "Bob Smith",
      "walletAddress": "0xB12C34Ff1234aB56C8d567ea",
      "investorType": "Company",
      "business": true,
      "residency": "CA",
      "nationality": "Canadian",
      "status": "Rejected",
    },
    {
      "id": "3",
      "name": "Carlos Diaz",
      "walletAddress": "0xC34De87F6f34aB89Db0F123e",
      "investorType": "Individual",
      "business": false,
      "residency": "MX",
      "nationality": "Mexican",
      "status": "Verified",
    },
    {
      "id": "4",
      "name": "Dana Lee",
      "walletAddress": "0xD56Ac70F5g56bD84Ef7e367g",
      "investorType": "Company",
      "business": true,
      "residency": "KR",
      "nationality": "Korean",
      "status": "Verified",
    },
    {
      "id": "5",
      "name": "Elena Romanov",
      "walletAddress": "0xE67Df7658c67cF78Fg1f245a",
      "investorType": "Individual",
      "business": false,
      "residency": "RU",
      "nationality": "Russian",
      "status": "Expired",
    },
    {
      "id": "6",
      "name": "Fernando Garcia",
      "walletAddress": "0xF78E87679d789Gi2H123j567a",
      "investorType": "Company",
      "business": true,
      "residency": "BR",
      "nationality": "Brazilian",
      "status": "Rejected",
    },
    {
      "id": "7",
      "name": "Grace Wong",
      "walletAddress": "0xG89Fe67878d890Hj5K789aE4",
      "investorType": "Individual",
      "business": false,
      "residency": "CN",
      "nationality": "Chinese",
      "status": "Verified",
    },
    {
      "id": "8",
      "name": "Grace Wong",
      "walletAddress": "0xG89Fe67878d890Hj5K789aE4",
      "investorType": "Individual",
      "business": false,
      "residency": "CN",
      "nationality": "Chinese",
      "status": "Verified",
    },
    {
      "id": "9",
      "name": "Grace Wong",
      "walletAddress": "0xG89Fe67878d890Hj5K789aE4",
      "investorType": "Individual",
      "business": false,
      "residency": "CN",
      "nationality": "Chinese",
      "status": "Verified",
    },
    {
      "id": "10",
      "name": "Grace Wong",
      "walletAddress": "0xG89Fe67878d890Hj5K789aE4",
      "investorType": "Individual",
      "business": false,
      "residency": "CN",
      "nationality": "Chinese",
      "status": "Verified",
    },
    {
      "id": "11",
      "name": "Grace Wong",
      "walletAddress": "0xG89Fe67878d890Hj5K789aE4",
      "investorType": "Individual",
      "business": false,
      "residency": "CN",
      "nationality": "Chinese",
      "status": "Verified",
    },
    {
      "id": "12",
      "name": "Grace Wong",
      "walletAddress": "0xG89Fe67878d890Hj5K789aE4",
      "investorType": "Individual",
      "business": false,
      "residency": "CN",
      "nationality": "Chinese",
      "status": "Verified",
    },
    {
      "id": "13",
      "name": "Grace Wong",
      "walletAddress": "0xG89Fe67878d890Hj5K789aE4",
      "investorType": "Individual",
      "business": false,
      "residency": "CN",
      "nationality": "Chinese",
      "status": "Verified",
    },
    {
      "id": "14",
      "name": "Grace Wong",
      "walletAddress": "0xG89Fe67878d890Hj5K789aE4",
      "investorType": "Individual",
      "business": false,
      "residency": "CN",
      "nationality": "Chinese",
      "status": "Verified",
    },
    {
      "id": "15",
      "name": "Grace Wong",
      "walletAddress": "0xG89Fe67878d890Hj5K789aE4",
      "investorType": "Individual",
      "business": false,
      "residency": "CN",
      "nationality": "Chinese",
      "status": "Verified",
    },{
      "id": "16",
      "name": "Hannah White",
      "walletAddress": "0xH90Gh67890i890Jk6L890bE5",
      "investorType": "Company",
      "business": true,
      "residency": "UK",
      "nationality": "British",
      "status": "Verified",
    },
    {
      "id": "17",
      "name": "Ian Green",
      "walletAddress": "0xI01Hi78901j901Kl7L901cF6",
      "investorType": "Individual",
      "business": false,
      "residency": "AU",
      "nationality": "Australian",
      "status": "Expired",
    },
    {
      "id": "18",
      "name": "Julia Black",
      "walletAddress": "0xJ12Ji89012k912Lm8M912dG7",
      "investorType": "Company",
      "business": true,
      "residency": "NZ",
      "nationality": "New Zealander",
      "status": "Rejected",
    },
    {
      "id": "19",
      "name": "Kevin Brown",
      "walletAddress": "0xK23Kj90123l123Mn9N123eH8",
      "investorType": "Individual",
      "business": false,
      "residency": "IE",
      "nationality": "Irish",
      "status": "Verified",
    },
    {
      "id": "20",
      "name": "Laura Blue",
      "walletAddress": "0xL34Lk01234m234No0O234fI9",
      "investorType": "Company",
      "business": true,
      "residency": "IN",
      "nationality": "Indian",
      "status": "Expired",
    },
    {
      "id": "21",
      "name": "Michael Red",
      "walletAddress": "0xM45Ml12345n345Op1P345gJ0",
      "investorType": "Individual",
      "business": false,
      "residency": "JP",
      "nationality": "Japanese",
      "status": "Rejected",
    },
    {
      "id": "22",
      "name": "Nancy Yellow",
      "walletAddress": "0xN56Nn23456o456Pq2Q456hK1",
      "investorType": "Company",
      "business": true,
      "residency": "FR",
      "nationality": "French",
      "status": "Verified",
    },
    {
      "id": "23",
      "name": "Oliver Purple",
      "walletAddress": "0xO67On34567p567Qr3R567iL2",
      "investorType": "Individual",
      "business": false,
      "residency": "IT",
      "nationality": "Italian",
      "status": "Expired",
    },
    {
      "id": "24",
      "name": "Patricia Orange",
      "walletAddress": "0xP78Po45678q678Rs4S678jM3",
      "investorType": "Company",
      "business": true,
      "residency": "ES",
      "nationality": "Spanish",
      "status": "Rejected",
    },
    {
      "id": "25",
      "name": "Quentin Gray",
      "walletAddress": "0xQ89Qp56789r789St5T789kN4",
      "investorType": "Individual",
      "business": false,
      "residency": "PT",
      "nationality": "Portuguese",
      "status": "Verified",
    },
    {
      "id": "26",
      "name": "Rebecca Pink",
      "walletAddress": "0xR90Rp67890s890Tu6U890lO5",
      "investorType": "Company",
      "business": true,
      "residency": "DE",
      "nationality": "German",
      "status": "Expired",
    },
    {
      "id": "27",
      "name": "Steven Cyan",
      "walletAddress": "0xS01Sq78901t901Uv7V901mP6",
      "investorType": "Individual",
      "business": false,
      "residency": "SE",
      "nationality": "Swedish",
      "status": "Rejected",
    },
    {
      "id": "28",
      "name": "Teresa Magenta",
      "walletAddress": "0xT12Tt89012u112Vw8W012nQ7",
      "investorType": "Company",
      "business": true,
      "residency": "NO",
      "nationality": "Norwegian",
      "status": "Verified",
    },
    {
      "id": "29",
      "name": "Ursula Lime",
      "walletAddress": "0xU23Uu90123v223Wx9X123oR8",
      "investorType": "Individual",
      "business": false,
      "residency": "DK",
      "nationality": "Danish",
      "status": "Expired",
    },
    {
      "id": "30",
      "name": "Victor Teal",
      "walletAddress": "0xV34Vv01234w334Xy0Y234pS9",
      "investorType": "Company",
      "business": true,
      "residency": "FI",
      "nationality": "Finnish",
      "status": "Rejected",
    },{
      "id": "31",
      "name": "Grace Wong",
      "walletAddress": "0xG89Fe67878d890Hj5K789aE4",
      "investorType": "Individual",
      "business": false,
      "residency": "CN",
      "nationality": "Chinese",
      "status": "Verified",
    },{
      "id": "32",
      "name": "Hannah White",
      "walletAddress": "0xH90Gh67890i890Jk6L890bE5",
      "investorType": "Company",
      "business": true,
      "residency": "UK",
      "nationality": "British",
      "status": "Verified",
    },
    {
      "id": "33",
      "name": "Ian Green",
      "walletAddress": "0xI01Hi78901j901Kl7L901cF6",
      "investorType": "Individual",
      "business": false,
      "residency": "AU",
      "nationality": "Australian",
      "status": "Expired",
    },
    {
      "id": "34",
      "name": "Julia Black",
      "walletAddress": "0xJ12Ji89012k912Lm8M912dG7",
      "investorType": "Company",
      "business": true,
      "residency": "NZ",
      "nationality": "New Zealander",
      "status": "Rejected",
    },
    {
      "id": "35",
      "name": "Kevin Brown",
      "walletAddress": "0xK23Kj90123l123Mn9N123eH8",
      "investorType": "Individual",
      "business": false,
      "residency": "IE",
      "nationality": "Irish",
      "status": "Verified",
    },
    {
      "id": "36",
      "name": "Laura Blue",
      "walletAddress": "0xL34Lk01234m234No0O234fI9",
      "investorType": "Company",
      "business": true,
      "residency": "IN",
      "nationality": "Indian",
      "status": "Expired",
    },
    {
      "id": "37",
      "name": "Michael Red",
      "walletAddress": "0xM45Ml12345n345Op1P345gJ0",
      "investorType": "Individual",
      "business": false,
      "residency": "JP",
      "nationality": "Japanese",
      "status": "Rejected",
    },
    {
      "id": "38",
      "name": "Nancy Yellow",
      "walletAddress": "0xN56Nn23456o456Pq2Q456hK1",
      "investorType": "Company",
      "business": true,
      "residency": "FR",
      "nationality": "French",
      "status": "Verified",
    },
    {
      "id": "39",
      "name": "Oliver Purple",
      "walletAddress": "0xO67On34567p567Qr3R567iL2",
      "investorType": "Individual",
      "business": false,
      "residency": "IT",
      "nationality": "Italian",
      "status": "Expired",
    },
    {
      "id": "40",
      "name": "Patricia Orange",
      "walletAddress": "0xP78Po45678q678Rs4S678jM3",
      "investorType": "Company",
      "business": true,
      "residency": "ES",
      "nationality": "Spanish",
      "status": "Rejected",
    },
    {
      "id": "41",
      "name": "Quentin Gray",
      "walletAddress": "0xQ89Qp56789r789St5T789kN4",
      "investorType": "Individual",
      "business": false,
      "residency": "PT",
      "nationality": "Portuguese",
      "status": "Verified",
    },
    {
      "id": "42",
      "name": "Rebecca Pink",
      "walletAddress": "0xR90Rp67890s890Tu6U890lO5",
      "investorType": "Company",
      "business": true,
      "residency": "DE",
      "nationality": "German",
      "status": "Expired",
    },
    {
      "id": "43",
      "name": "Steven Cyan",
      "walletAddress": "0xS01Sq78901t901Uv7V901mP6",
      "investorType": "Individual",
      "business": false,
      "residency": "SE",
      "nationality": "Swedish",
      "status": "Rejected",
    },
    {
      "id": "44",
      "name": "Teresa Magenta",
      "walletAddress": "0xT12Tt89012u112Vw8W012nQ7",
      "investorType": "Company",
      "business": true,
      "residency": "NO",
      "nationality": "Norwegian",
      "status": "Verified",
    },
    {
      "id": "45",
      "name": "Ursula Lime",
      "walletAddress": "0xU23Uu90123v223Wx9X123oR8",
      "investorType": "Individual",
      "business": false,
      "residency": "DK",
      "nationality": "Danish",
      "status": "Expired",
    },
    {
      "id": "46",
      "name": "Victor Teal",
      "walletAddress": "0xV34Vv01234w334Xy0Y234pS9",
      "investorType": "Company",
      "business": true,
      "residency": "FI",
      "nationality": "Finnish",
      "status": "Rejected",
    }
  ]

  const pathname = usePathname();
  const router = useRouter();

  const onRowClickAction = (row: any) => {
    // Navigate to the investor details page if not on dashboard
    if (pathname !== "/dashboard") {
      router.push(`/dashboard/investors/${row.original.id}`);
    }
  }

  return (
    <div className="mx-auto">
      <DataTable columns={investorTableColumns} data={data} onRowClick={onRowClickAction} />
    </div>
  )
}